// flow-typed signature: f6c184b58f7b40b2c48d43856bbff418
// flow-typed version: <<STUB>>/async-dispatcher_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-dispatcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-dispatcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-dispatcher/lib/dispatch/DispatcherDispatchHandler' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/dispatch/index' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/dispatch/StoreDispatchHandler' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/dispatch/types' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/Dispatcher' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/index' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/middleware' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/Store' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/utils/asyncReduce' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/utils/combineMiddleware' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/utils/mapOfPromisesToMapPromise' {
  declare module.exports: any;
}

declare module 'async-dispatcher/lib/utils/Queue' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/dispatch/DispatcherDispatchHandler' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/dispatch/index' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/dispatch/StoreDispatchHandler' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/dispatch/types' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/Dispatcher' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/index' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/middleware' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/Store' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/utils/asyncReduce' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/utils/combineMiddleware' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/utils/mapOfPromisesToMapPromise' {
  declare module.exports: any;
}

declare module 'async-dispatcher/src/utils/Queue' {
  declare module.exports: any;
}

declare module 'async-dispatcher/type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-dispatcher/lib/dispatch/DispatcherDispatchHandler.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/dispatch/DispatcherDispatchHandler'>;
}
declare module 'async-dispatcher/lib/dispatch/index.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/dispatch/index'>;
}
declare module 'async-dispatcher/lib/dispatch/StoreDispatchHandler.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/dispatch/StoreDispatchHandler'>;
}
declare module 'async-dispatcher/lib/dispatch/types.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/dispatch/types'>;
}
declare module 'async-dispatcher/lib/Dispatcher.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/Dispatcher'>;
}
declare module 'async-dispatcher/lib/index.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/index'>;
}
declare module 'async-dispatcher/lib/middleware.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/middleware'>;
}
declare module 'async-dispatcher/lib/Store.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/Store'>;
}
declare module 'async-dispatcher/lib/utils/asyncReduce.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/utils/asyncReduce'>;
}
declare module 'async-dispatcher/lib/utils/combineMiddleware.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/utils/combineMiddleware'>;
}
declare module 'async-dispatcher/lib/utils/mapOfPromisesToMapPromise.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/utils/mapOfPromisesToMapPromise'>;
}
declare module 'async-dispatcher/lib/utils/Queue.js' {
  declare module.exports: $Exports<'async-dispatcher/lib/utils/Queue'>;
}
declare module 'async-dispatcher/src/dispatch/DispatcherDispatchHandler.js' {
  declare module.exports: $Exports<'async-dispatcher/src/dispatch/DispatcherDispatchHandler'>;
}
declare module 'async-dispatcher/src/dispatch/index.js' {
  declare module.exports: $Exports<'async-dispatcher/src/dispatch/index'>;
}
declare module 'async-dispatcher/src/dispatch/StoreDispatchHandler.js' {
  declare module.exports: $Exports<'async-dispatcher/src/dispatch/StoreDispatchHandler'>;
}
declare module 'async-dispatcher/src/dispatch/types.js' {
  declare module.exports: $Exports<'async-dispatcher/src/dispatch/types'>;
}
declare module 'async-dispatcher/src/Dispatcher.js' {
  declare module.exports: $Exports<'async-dispatcher/src/Dispatcher'>;
}
declare module 'async-dispatcher/src/index.js' {
  declare module.exports: $Exports<'async-dispatcher/src/index'>;
}
declare module 'async-dispatcher/src/middleware.js' {
  declare module.exports: $Exports<'async-dispatcher/src/middleware'>;
}
declare module 'async-dispatcher/src/Store.js' {
  declare module.exports: $Exports<'async-dispatcher/src/Store'>;
}
declare module 'async-dispatcher/src/utils/asyncReduce.js' {
  declare module.exports: $Exports<'async-dispatcher/src/utils/asyncReduce'>;
}
declare module 'async-dispatcher/src/utils/combineMiddleware.js' {
  declare module.exports: $Exports<'async-dispatcher/src/utils/combineMiddleware'>;
}
declare module 'async-dispatcher/src/utils/mapOfPromisesToMapPromise.js' {
  declare module.exports: $Exports<'async-dispatcher/src/utils/mapOfPromisesToMapPromise'>;
}
declare module 'async-dispatcher/src/utils/Queue.js' {
  declare module.exports: $Exports<'async-dispatcher/src/utils/Queue'>;
}
declare module 'async-dispatcher/type.js' {
  declare module.exports: $Exports<'async-dispatcher/type'>;
}
