// flow-typed signature: 8dc774d3f30bead060e944b13ca66dd6
// flow-typed version: <<STUB>>/babel-watch_v^2.0.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-watch/babel-watch' {
  declare module.exports: any;
}

declare module 'babel-watch/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-watch/babel-watch.js' {
  declare module.exports: $Exports<'babel-watch/babel-watch'>;
}
declare module 'babel-watch/runner.js' {
  declare module.exports: $Exports<'babel-watch/runner'>;
}
