// flow-typed signature: 9a02adc0a321db87a85cc98845b30ca4
// flow-typed version: <<STUB>>/express-device_v^0.4.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-device'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-device' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-device/example/app_with_parse' {
  declare module.exports: any;
}

declare module 'express-device/example/app' {
  declare module.exports: any;
}

declare module 'express-device/lib/device' {
  declare module.exports: any;
}

declare module 'express-device/test/app_no_partials/app' {
  declare module.exports: any;
}

declare module 'express-device/test/app/app' {
  declare module.exports: any;
}

declare module 'express-device/test/cloudfront_test' {
  declare module.exports: any;
}

declare module 'express-device/test/helpers_test' {
  declare module.exports: any;
}

declare module 'express-device/test/no_partials_test' {
  declare module.exports: any;
}

declare module 'express-device/test/view_route_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-device/example/app_with_parse.js' {
  declare module.exports: $Exports<'express-device/example/app_with_parse'>;
}
declare module 'express-device/example/app.js' {
  declare module.exports: $Exports<'express-device/example/app'>;
}
declare module 'express-device/index' {
  declare module.exports: $Exports<'express-device'>;
}
declare module 'express-device/index.js' {
  declare module.exports: $Exports<'express-device'>;
}
declare module 'express-device/lib/device.js' {
  declare module.exports: $Exports<'express-device/lib/device'>;
}
declare module 'express-device/test/app_no_partials/app.js' {
  declare module.exports: $Exports<'express-device/test/app_no_partials/app'>;
}
declare module 'express-device/test/app/app.js' {
  declare module.exports: $Exports<'express-device/test/app/app'>;
}
declare module 'express-device/test/cloudfront_test.js' {
  declare module.exports: $Exports<'express-device/test/cloudfront_test'>;
}
declare module 'express-device/test/helpers_test.js' {
  declare module.exports: $Exports<'express-device/test/helpers_test'>;
}
declare module 'express-device/test/no_partials_test.js' {
  declare module.exports: $Exports<'express-device/test/no_partials_test'>;
}
declare module 'express-device/test/view_route_test.js' {
  declare module.exports: $Exports<'express-device/test/view_route_test'>;
}
