// flow-typed signature: 7646ce2c12c7897e827d94b943a070b9
// flow-typed version: <<STUB>>/react-async-dispatcher_v^0.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-dispatcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-dispatcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-dispatcher/lib/dispatchWhenMounted' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/lib/getDispatcher' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/lib/index' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/lib/useActionCreator' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/lib/useDispatch' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/lib/useDispatcher' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/lib/useStoreState' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/dispatchWhenMounted' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/getDispatcher' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/index' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/useActionCreator' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/useDispatch' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/useDispatcher' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/src/useStoreState' {
  declare module.exports: any;
}

declare module 'react-async-dispatcher/type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-dispatcher/lib/dispatchWhenMounted.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/dispatchWhenMounted'>;
}
declare module 'react-async-dispatcher/lib/getDispatcher.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/getDispatcher'>;
}
declare module 'react-async-dispatcher/lib/index.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/index'>;
}
declare module 'react-async-dispatcher/lib/useActionCreator.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/useActionCreator'>;
}
declare module 'react-async-dispatcher/lib/useDispatch.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/useDispatch'>;
}
declare module 'react-async-dispatcher/lib/useDispatcher.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/useDispatcher'>;
}
declare module 'react-async-dispatcher/lib/useStoreState.js' {
  declare module.exports: $Exports<'react-async-dispatcher/lib/useStoreState'>;
}
declare module 'react-async-dispatcher/src/dispatchWhenMounted.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/dispatchWhenMounted'>;
}
declare module 'react-async-dispatcher/src/getDispatcher.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/getDispatcher'>;
}
declare module 'react-async-dispatcher/src/index.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/index'>;
}
declare module 'react-async-dispatcher/src/useActionCreator.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/useActionCreator'>;
}
declare module 'react-async-dispatcher/src/useDispatch.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/useDispatch'>;
}
declare module 'react-async-dispatcher/src/useDispatcher.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/useDispatcher'>;
}
declare module 'react-async-dispatcher/src/useStoreState.js' {
  declare module.exports: $Exports<'react-async-dispatcher/src/useStoreState'>;
}
declare module 'react-async-dispatcher/type.js' {
  declare module.exports: $Exports<'react-async-dispatcher/type'>;
}
